#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Build Patrick Moore's Caldwell catalogue (1995, 109 objects) as an uptonight
target list, from Gary Imm's Deep Sky Compendium.

    curl -o cald.wiki 'https://en.wikipedia.org/w/index.php?title=Caldwell_catalogue&action=raw'
    scripts/caldwell2yaml.py IMM_Compendium_2026.xlsx cald.wiki > internal/catalog/targets/Caldwell.yaml

Standard library only. The Compendium row carrying "Caldwell N" (cross-ID
column AM or the alternative IDs) gives position, size, type, magnitude,
surface brightness and common names. It puts C24 (NGC 1275) and C35 (NGC
4889) on the Abell galaxy clusters around them and has no row of their own,
so those come from OpenNGC.yaml (OPENNGC); regenerate after it. Where the
Compendium images a larger complex (C68 NGC 6726 for NGC 6729, C82 NGC 6188
for NGC 6193) its row is kept, and Wikipedia's designation and common name
are added to the description where the Compendium lacks them.
"""

import json
import re
import sys

from imm2yaml import aliases, designation, kind, num, position, sexagesimal
from mwsc2yaml import entries
from wiki2yaml import LINK, REF

COUNT = 109
OPENNGC = {24: "NGC 1275", 35: "NGC 4889"}  # Caldwell's galaxy, not the Compendium's cluster


def wiki(path):
    """Caldwell number -> (designations, common names) from the Wikipedia table."""
    out = {}
    for chunk in open(path, encoding="utf-8").read().split("\n|-"):
        cells = [" ".join(LINK.sub(r"\1", REF.sub(" ", c)).replace("&nbsp;", " ").split())
                 for c in chunk.splitlines()[1:4]]
        if len(cells) < 3 or not (m := re.fullmatch(r"\| C(\d+)", cells[0])):
            continue
        ids = [d for d in re.split(r"\s*(?:&|,|/|\band\b)\s*", cells[1].lstrip("| ")) if re.search(r"\d", d)]
        common = re.sub(r'^\|?\s*(style="[^"]*"\s*\|)?', "", cells[2]).strip()
        out[int(m.group(1))] = (ids, [c for c in re.split(r"''\s*,\s*''|,", common.strip("' ")) if c.strip()])
    if sorted(out) != list(range(1, COUNT + 1)):
        sys.exit(f"error: want C1-C{COUNT} once each in the Wikipedia table, got {len(out)}")
    return out


def main():
    index, table = aliases(sys.argv[1]), wiki(sys.argv[2])
    ngc = {e["name"]: e for e in entries("OpenNGC.yaml")}
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    print("# Generated by scripts/caldwell2yaml.py: the Caldwell catalogue (Moore 1995) from")
    print("# Gary Imm's Deep Sky Compendium (2026) - data (c) Gary Imm - and OpenNGC (CC BY-SA 4.0).")
    for n in range(1, COUNT + 1):
        ids, common = table[n]
        if n in OPENNGC:
            e = ngc[OPENNGC[n]]
            print('- constellation: ""')  # the loader computes it from RA/Dec
            for k in ("bmag", "bsurfbr"):
                if k in e:
                    print(f"  {k}: {e[k]}")
            print(f'  dec: {q(e["dec"])}')
            print(f"  description: {q(', '.join([OPENNGC[n]] + common))}")
            print(f'  mag: {e["mag"]}')
            print(f"  name: {q(f'C {n}')}")
            print(f'  ra: {q(e["ra"])}')
            print(f'  size: {e["size"]}')
            print(f'  type: {q(e["type"])}')
            continue
        rows = list({id(r): r for r in index.get(f"Caldwell {n}", []) + index.get(f"Caldwell{n}", [])}.values())
        if len(rows) != 1:
            sys.exit(f"error: C{n}: want one Compendium row, got {len(rows)}")
        r = rows[0]
        ra, dec = position(r)
        size, mag, surfbr = num(r.get("G")), num(r.get("T")), num(r.get("U"))
        # "Butterfly Nebula (3 of 3)", "Double Cluster (with NGC 884)": notes, not names.
        nick = re.sub(r"\s*\([^)]*\)", "", " ".join((r.get("Q") or "").split()))
        # Wikipedia's designation is Caldwell's object (NGC 4038 of the Arp 244 row).
        desc = [designation(r["A"])] + [designation(d) for d in ids] + re.split(r"\s*,\s*", nick)
        named = {d.lower() for d in desc}
        desc += [c.strip() for c in common if c.strip().lower() not in named]
        print('- constellation: ""')
        print(f"  dec: {q(sexagesimal(dec))}")
        print(f"  description: {q(', '.join(d for d in dict.fromkeys(desc) if d))}")
        print(f"  mag: {mag if mag is not None else -9999}")
        print(f"  name: {q(f'C {n}')}")
        print(f"  ra: {q(sexagesimal(ra, hours=True))}")
        print(f"  size: {size if size is not None else -9999}")
        if surfbr is not None:
            print(f"  surfbr: {round(surfbr, 2)}")
        print(f"  type: {q(kind(r))}")


if __name__ == "__main__":
    main()
