#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Convert the published Planetary Nebulae.net discoveries (Le Du et al. 2022,
CDS J/A+A/666/A152) to an uptonight target list.

    curl -O https://cdsarc.cds.unistra.fr/ftp/J/A+A/666/A152/table1.dat
    curl -O https://cdsarc.cds.unistra.fr/ftp/J/A+A/666/A152/table2.dat
    scripts/ledu2yaml.py table1.dat table2.dat > internal/catalog/targets/PNnet.yaml

Standard library only. table1 holds the spectroscopically confirmed true,
likely and possible PNe, table2 the candidates still unobserved; the
planetarynebulae.net site has newer ones (scripts/pnnet2yaml.py, local only).
Fixed columns per the CDS ReadMe: 1-14 name, 43-52 PN G, 54-64 RA, 66-77 Dec,
79-87 size (arcmin, "a x b"), 237-240 HASH status.
"""

import json
import sys

STATUS = {"T": "True PN", "L": "Likely PN", "P": "Possible PN", "c": "New candidate"}


def main():
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    print("# Generated by scripts/ledu2yaml.py from Le Du et al. 2022, A&A 666, A152")
    print("# (CDS J/A+A/666/A152): PNe and candidates discovered by the planetarynebulae.net group.")
    for path in sys.argv[1:]:
        for line in open(path, encoding="ascii"):
            line = line.ljust(240)
            name, status = " ".join(line[0:14].split()), STATUS[line[236:240].strip()]
            sizes = [float(v) for v in line[78:87].split("x") if v.strip()]
            print('- constellation: ""')  # the loader computes it from RA/Dec
            print(f"  dec: {q(line[65] + line[66:77])}")
            print(f"  description: {q(f'{status}, PN G {line[42:52].strip()}')}")
            print(f"  name: {q(name)}")
            print(f"  ra: {q(line[53:64])}")
            print(f"  size: {max(sizes) if sizes else -9999}")
            print('  type: "Planetary Nebula"')


if __name__ == "__main__":
    main()
