#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Build the Melotte catalogue (Melotte 1915, 245 clusters) as an uptonight
target list.

    curl -o mel.wiki 'https://en.wikipedia.org/w/index.php?title=Melotte_catalogue&action=raw'
    scripts/mel2yaml.py mel.wiki > internal/catalog/targets/Melotte.yaml

Standard library only. The Wikipedia table gives each Mel number its NGC/IC
designation and common name; position, size and type come from MWSC.yaml (by
NGC/IC number, else "Melotte N"), then OpenNGC/OpenIC.yaml, then
GaryImmFull.yaml (the Hyades, which MWSC lacks); Mel 31 and Mel 186 are in
none of them and come from SIMBAD. Regenerate it after MWSC.yaml.
"""

import json
import re
import sys

from imm2yaml import sexagesimal
from mwsc2yaml import entries

LINK = re.compile(r"\[\[(?:[^|\]]*\|)?([^\]]*)\]\]")  # [[target|text]] -> text
REF = re.compile(r"<ref.*?(?:</ref>|/>)")
# In no embedded list: SIMBAD "Cl Melotte 31" / "Cl Melotte 186" (J2000 deg, arcmin).
SIMBAD = {
    "Melotte 31": (79.54166, 33.37361, -9999),
    "Melotte 186": (270.59792, 3.26, 187.4),
}


def rows(path):
    """(number, NGC/IC cell, other names) per table row."""
    for chunk in open(path, encoding="utf-8").read().split("\n|-"):
        line = chunk.strip().splitlines()[0] if chunk.strip() else ""
        cells = [LINK.sub(r"\1", REF.sub("", c)).strip() for c in line.lstrip("| ").split("||")]
        m = re.fullmatch(r"Mel (\d+)", cells[0])
        if m and len(cells) > 2:
            yield int(m.group(1)), cells[1].strip("- "), cells[2]


def main():
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    known = {n: {"name": n, "ra": sexagesimal(ra, hours=True), "dec": sexagesimal(dec), "size": size,
                 "type": "Open Cluster"} for n, (ra, dec, size) in SIMBAD.items()}
    for name in ("GaryImmFull.yaml", "OpenIC.yaml", "OpenNGC.yaml", "MWSC.yaml"):  # later lists win
        known.update((f["name"], f) for f in entries(name))
    out = list(rows(sys.argv[1]))
    if sorted(n for n, _, _ in out) != list(range(1, 246)):
        sys.exit(f"error: want Mel 1-245 once each, got {len(out)} rows")
    print("# Generated by scripts/mel2yaml.py: the Melotte catalogue (1915), cross-identified")
    print("# with NGC/IC via Wikipedia; positions, sizes and types from MWSC, OpenNGC and GaryImmFull.")
    for n, ids, other in out:
        ident = re.match(r"(?:NGC|IC) \d+", ids)
        f = known.get(ident.group(0) if ident else "") or known.get(f"Melotte {n}")
        if f is None:
            sys.exit(f"error: Mel {n} ({ids or 'no NGC/IC'}) not found in any list")
        messier = re.match(r"M \d+", f.get("description", ""))
        desc = " ".join(filter(None, (messier and messier.group(0), ids, other)))
        print('- constellation: ""')  # the loader computes it from RA/Dec
        print(f"  dec: {q(f['dec'])}")
        print(f"  description: {q(desc)}")
        print(f"  name: {q(f'Mel {n}')}")
        print(f"  ra: {q(f['ra'])}")
        print(f"  size: {f['size']}")
        print(f"  type: {q(f['type'])}")


if __name__ == "__main__":
    main()
