#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Convert the Milky Way Star Clusters catalogue (Kharchenko et al. 2013,
CDS J/A+A/558/A53) to an uptonight target list.

    curl -O https://cdsarc.cds.unistra.fr/ftp/J/A+A/558/A53/catalog.dat
    scripts/mwsc2yaml.py catalog.dat > internal/catalog/targets/MWSC.yaml

Standard library only. Fixed columns per the CDS ReadMe: 6-22 name, 24 type,
25 object/candidate, 26-34 RA (hours), 35-42 Dec (deg), 66-72 r1 (deg).
The size is the diameter of r1, the cluster's central part: r2 is the whole
membership halo, 2-3 times the visual size (NGC 869 r1 29', r2 64').
Messier clusters get "M nn" and their common name as description, joined on
the NGC/IC number in Messier.yaml's description.
"""

import json
import os
import re
import sys

from imm2yaml import sexagesimal

# MWSC type -> (type, description note). Associations (NGC 4755, NGC 6231)
# and moving groups are star fields: "Open Cluster" gets them the cluster sky
# weighting in scoring.skyK.
TYPES = {
    "": ("Open Cluster", None),
    "r": ("Open Cluster", "remnant"),
    "a": ("Open Cluster", "association"),
    "m": ("Open Cluster", "moving group"),
    "g": ("Globular Cluster", None),
    "n": ("Cluster Nebulosity", None),  # Herschel400's spelling
    "s": ("Asterism", None),
}

TARGETS = os.path.join(os.path.dirname(__file__), "../internal/catalog/targets")


def entries(name):
    """The entries of a flat target list in TARGETS as dicts of raw strings
    (quotes stripped), without a YAML library."""
    for entry in open(os.path.join(TARGETS, name), encoding="utf-8").read().split("\n- "):
        f = dict(re.findall(r"^\s*-?\s*(\w+): ?(.*)$", entry, re.M))
        if "name" in f:
            yield {k: v[1:-1] if v[:1] == '"' else v for k, v in f.items()}


def messier():
    """MWSC name -> "M nn common name", for Messier.yaml's clusters only: M 24
    (star cloud) and M 73 (asterism) share an NGC number with something else."""
    out = {"Melotte 22": "M 45 Pleiades"}  # no NGC number in Messier.yaml
    for f in entries("Messier.yaml"):
        m = re.match(r"((?:NGC|IC) \d+)\s*(.*)", f.get("description", ""))
        if m and f.get("type") in ("Open Cluster", "Globular Cluster"):
            common = m.group(2).replace("\\xB9", "'")  # Ptolemy\xB9s: a mangled apostrophe
            out[m.group(1)] = f"{f['name']} {common}".strip()
    return out


def main():
    alias = messier()
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    print("# Generated by scripts/mwsc2yaml.py from the Milky Way Star Clusters catalogue")
    print("# (Kharchenko et al. 2013, A&A 558, A53; CDS J/A+A/558/A53).")
    print("# size is the diameter of r1, the cluster's central part.")
    for line in open(sys.argv[1], encoding="ascii"):
        line = line.ljust(80)
        typ, cand = line[23].strip(), line[24] == "c"
        name = line[5:22].strip().replace("_", " ")
        kind, note = TYPES[typ]
        desc = " ".join(filter(None, (alias.get(name), note, cand and "candidate")))
        print('- constellation: ""')  # the loader computes it from RA/Dec
        print(f"  dec: {q(sexagesimal(float(line[34:42])))}")
        print(f"  description: {q(desc)}")
        print(f"  name: {q(name)}")
        print(f"  ra: {q(sexagesimal(float(line[25:34]) * 15, hours=True))}")
        print(f"  size: {round(float(line[65:72]) * 120, 1)}")
        print(f"  type: {q(kind)}")


if __name__ == "__main__":
    main()
