#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Convert the OpenNGC database (Mattia Verga, CC BY-SA 4.0) to the OpenNGC
and OpenIC uptonight target lists.

    curl -O https://raw.githubusercontent.com/mattiaverga/OpenNGC/master/database_files/NGC.csv
    scripts/openngc2yaml.py NGC.csv NGC > internal/catalog/targets/OpenNGC.yaml
    scripts/openngc2yaml.py NGC.csv IC > internal/catalog/targets/OpenIC.yaml

Standard library only. Names, types, positions and sizes follow uptonight's
own conversion (type abbreviations it did not expand stay as OpenNGC spells
them); mag is the V magnitude, bmag the B magnitude and bsurfbr the mean
B-band surface brightness within the 25 mag isophote (mag/arcsec^2; V-band
surfbr is the Compendium's), each left out when OpenNGC has none. Where
OpenNGC has no V magnitude, GaryImmFull.yaml's (the Compendium's, also V)
is used, and its V-band surface brightness is added as surfbr, so regenerate
GaryImmFull first. The description is the Messier number, the
NGC/IC cross-identifications and the common names.
"""

import csv
import json
import re
import sys

from mwsc2yaml import lookup

TYPES = {"G": "Galaxy", "OCl": "Open Cluster", "GCl": "Globular Cluster", "GPair": "Galaxy Pair", "Dup": "Duplicate",
         "PN": "Planetary Nebula", "Neb": "Nebula", "HII": "HII Emission Nebula", "Cl+N": "Cl+N Emission Nebula",
         "RfN": "Reflection Nebula", "SNR": "Supernova Remnant"}
CONSTELLATIONS = {
    "And": "Andromeda", "Ant": "Antlia", "Aps": "Apus", "Aql": "Aquila", "Aqr": "Aquarius", "Ara": "Ara",
    "Ari": "Aries", "Aur": "Auriga", "Boo": "Boötes", "Cae": "Caelum", "Cam": "Camelopardalis",
    "Cap": "Capricornus", "Car": "Carina", "Cas": "Cassiopeia", "Cen": "Centaurus", "Cep": "Cepheus",
    "Cet": "Cetus", "Cha": "Chamaeleon", "Cir": "Circinus", "CMa": "Canis Major", "CMi": "Canis Minor",
    "Cnc": "Cancer", "Col": "Columba", "Com": "Coma Berenices", "CrA": "Corona Australis",
    "CrB": "Corona Borealis", "Crt": "Crater", "Cru": "Crux", "Crv": "Corvus", "CVn": "Canes Venatici",
    "Cyg": "Cygnus", "Del": "Delphinus", "Dor": "Dorado", "Dra": "Draco", "Equ": "Equuleus", "Eri": "Eridanus",
    "For": "Fornax", "Gem": "Gemini", "Gru": "Grus", "Her": "Hercules", "Hor": "Horologium", "Hya": "Hydra",
    "Hyi": "Hydrus", "Ind": "Indus", "Lac": "Lacerta", "Leo": "Leo", "Lep": "Lepus", "Lib": "Libra",
    "LMi": "Leo Minor", "Lup": "Lupus", "Lyn": "Lynx", "Lyr": "Lyra", "Men": "Mensa", "Mic": "Microscopium",
    "Mon": "Monoceros", "Mus": "Musca", "Nor": "Norma", "Oct": "Octans", "Oph": "Ophiuchus", "Ori": "Orion",
    "Pav": "Pavo", "Peg": "Pegasus", "Per": "Perseus", "Phe": "Phoenix", "Pic": "Pictor", "PsA": "Piscis Austrinus",
    "Psc": "Pisces", "Pup": "Puppis", "Pyx": "Pyxis", "Ret": "Reticulum", "Scl": "Sculptor", "Sco": "Scorpius",
    "Sct": "Scutum", "Se1": "Serpens", "Se2": "Serpens", "Sex": "Sextans", "Sge": "Sagitta", "Sgr": "Sagittarius", "Tau": "Taurus",
    "Tel": "Telescopium", "Tri": "Triangulum", "TrA": "Triangulum Australe", "Tuc": "Tucana", "UMa": "Ursa Major",
    "UMi": "Ursa Minor", "Vel": "Vela", "Vir": "Virgo", "Vol": "Volans", "Vul": "Vulpecula",
}


def name(cat, ids):
    """'0618,0627' -> 'NGC 618, NGC 627'; 'NGC0190 NED01' -> 'NGC 190 NED01'."""
    return ", ".join(re.sub(r"^(?:NGC|IC)?0*(\d+)", rf"{cat} \1", i.strip()) for i in ids.split(",") if i.strip())


def sexagesimal(v):
    """'+07:12:60.0' (IC 3322A) -> '+07 13 00.0': 60 seconds carried, through the minutes if need be."""
    d, m, sec = v.split(":")
    if float(sec) >= 60:
        print(f"warning: {v}: 60 seconds carried", file=sys.stderr)
        sign, total = d[0] if d[0] in "+-" else "", abs(int(d)) * 3600 + int(m) * 60 + float(sec)
        d, m, sec = f"{sign}{int(total // 3600):02d}", f"{int(total % 3600 // 60):02d}", f"{total % 60:04.1f}"
    return " ".join((d, m, sec))


def main():
    path, cat = sys.argv[1], sys.argv[2]
    if cat not in ("NGC", "IC"):
        sys.exit("usage: openngc2yaml.py NGC.csv NGC|IC")
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    vmag, vsurfbr = lookup("mag", ("GaryImmFull.yaml",)), lookup("surfbr", ("GaryImmFull.yaml",))
    print(f"# Generated by scripts/openngc2yaml.py from OpenNGC (https://github.com/mattiaverga/OpenNGC,")
    print("# Mattia Verga, CC BY-SA 4.0): the", "NGC" if cat == "NGC" else "IC", "objects of NGC.csv.")
    for r in csv.DictReader(open(path, encoding="utf-8"), delimiter=";"):
        if not r["Name"].startswith(cat):
            continue
        if not r["RA"] or not r["Dec"]:
            print(f"warning: {r['Name']}: no RA/Dec, skipped", file=sys.stderr)
            continue
        desc = ", ".join(filter(None, (r["M"] and f"M {int(r['M'])}", name("NGC", r["NGC"]), name("IC", r["IC"]),
                                       ", ".join(c.strip() for c in r["Common names"].split(",") if c.strip()))))
        if r["B-Mag"]:
            print(f"- bmag: {r['B-Mag']}")
        if r["SurfBr"]:
            print(f"{'-' if not r['B-Mag'] else ' '} bsurfbr: {r['SurfBr']}")
        print(f"{'-' if not r['B-Mag'] and not r['SurfBr'] else ' '} constellation: {q(CONSTELLATIONS[r['Const']])}")
        print(f"  dec: {q(sexagesimal(r['Dec']))}")
        print(f"  description: {q(desc)}")
        n = name(cat, r["Name"])
        print(f"  mag: {r['V-Mag'] or vmag.get(n, -9999)}")
        print(f"  name: {q(n)}")
        print(f"  ra: {q(sexagesimal(r['RA']))}")
        print(f"  size: {r['MajAx'] or -9999}")
        if n in vsurfbr:
            print(f"  surfbr: {vsurfbr[n]}")
        print(f"  type: {q(TYPES.get(r['Type'], r['Type']))}")


if __name__ == "__main__":
    main()
