#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Fetch the Planetary Nebulae.net catalogue (French amateur PN discoveries,
https://planetarynebulae.net/) into an uptonight target list.

    scripts/pnnet2yaml.py > internal/catalog/targets/PNnet.yaml

PN.net is "all rights reserved"; its authors gave written permission to fetch
it and embed the result (October 2026). Two requests: the search page
(for the current list of discoverer checkboxes), then one search with all of
them ticked. Keeps true, likely and possible PNe and new candidates (status in
the description); objects PN.net classifies as something else are dropped.
Standard library only.
"""

import html
import json
import re
import sys
import urllib.parse
import urllib.request

URL = "https://planetarynebulae.net/EN/page_recherche.php"
UA = "astro-recommender (https://github.com/dkorunic/astro-recommender)"
KEEP = {"True PN", "Likely PN", "Possible PN", "New candidate"}
SEXA = re.compile(r"([+-]?)(\d{1,2}):(\d{1,2}):(\d{1,2}(?:\.\d+)?)")


def get(data=None):
    body = urllib.parse.urlencode(data).encode() if data else None
    req = urllib.request.Request(URL, data=body, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read().decode("utf-8", errors="replace")


def cells(row):
    return [" ".join(html.unescape(re.sub(r"<[^>]*>", " ", c)).split())
            for c in re.findall(r"<td[^>]*>(.*?)</td>", row, re.S)]


def sexagesimal(v, hours):
    """"05:53:50,86" -> "05 53 50.86", or None when malformed or out of range."""
    m = SEXA.fullmatch(v.replace(",", "."))
    if not m:
        return None
    sign, d, mi, s = m.groups()
    deg = int(d) + int(mi) / 60 + float(s) / 3600
    if int(mi) >= 60 or float(s) >= 60 or (deg >= 24 if hours else deg > 90):
        return None
    return f"{sign or ('' if hours else '+')}{int(d):02d} {int(mi):02d} {s}"


def size(v):
    """Major axis in arcmin from "4,8 min d'arc" or "2 x 1 min d'arc"; -9999 if none."""
    nums = [float(n) for n in re.findall(r"\d+(?:\.\d+)?", v.replace(",", "."))]
    return max(nums) if nums else -9999


def main():
    boxes = sorted(set(re.findall(r'name="(chk_[^"]+)"', get())))
    if not boxes:
        sys.exit("error: no checkboxes on the search page, has the site changed?")
    page = get({**{b: "on" for b in boxes}, "AD_debut": "-2", "AD_fin": "-2"})
    rows = [cells(r) for r in re.split(r"<tr>", page) if "page_np.php?id=" in r]
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    print("# Generated by scripts/pnnet2yaml.py from Planetary Nebulae.net")
    print("# (https://planetarynebulae.net/, (c) Planetary Nebulae net, all rights reserved), used with permission.")
    kept = 0
    for c in rows:
        if len(c) < 6 or c[5] not in KEEP:
            continue
        name, png, ra, dec, sz, status = c[:6]
        png = png.replace("PN-G", "PN G")  # as in PNnet.yaml
        ra, dec = sexagesimal(ra, True), sexagesimal(dec, False)
        if not ra or not dec:
            print(f"warning: {name}: bad coordinates {c[2]!r} {c[3]!r}, skipped", file=sys.stderr)
            continue
        kept += 1
        print('- constellation: ""')  # the loader computes it from RA/Dec
        print(f"  dec: {q(dec)}")
        print(f"  description: {q(f'{status}, {png}')}")
        print(f"  name: {q(name)}")
        print(f"  ra: {q(ra)}")
        print(f"  size: {size(sz)}")
        print('  type: "Planetary Nebula"')
    print(f"{len(rows)} objects, {kept} kept", file=sys.stderr)
    if not kept:
        sys.exit("error: nothing parsed, has the site changed?")


if __name__ == "__main__":
    main()
