#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Dinko Korunic <dinko.korunic@gmail.com>
# SPDX-License-Identifier: MIT
"""Build the Sharpless (1959) catalogue of 313 H II regions as an uptonight
target list, cross-identified with Gary Imm's Deep Sky Compendium.

    curl -o sh2.tsv 'https://vizier.cds.unistra.fr/viz-bin/asu-tsv?-source=VII/20&-out.all&-out.max=400&-out.add=_RAJ,_DEJ&-oc.form=dec'
    curl -o sh2.wiki 'https://en.wikipedia.org/w/index.php?title=Sharpless_catalog&action=raw'
    scripts/sharpless2yaml.py sh2.tsv sh2.wiki IMM_Compendium_2026.xlsx > internal/catalog/targets/Sharpless.yaml

Standard library only. CDS VII/20 gives every object's position (B1900,
precessed by VizieR to J2000) and diameter. The Compendium row named Sh2-N
(or carrying it as an alternative ID), else the one cross-identified with it
(column BB), gives the type, magnitude and surface brightness, a common name,
and the position, since Sharpless's B1900 positions, read off the BD, are off
by up to ~15' (NGC 6302); its size only for a row that is the Sharpless
object itself, since a cross-identified M 16 is a part of Sh2-49. A row
farther than max(20', half the diameter) is a Compendium typo (Sh2-210 is
4.6 degrees off) or another object, and is ignored with a warning, unless
SIMBAD confirms it (TRUSTED: there Sharpless is the one off). Wikipedia
adds the common names of the notable ones.
"""

import json
import math
import re
import sys

from imm2yaml import aliases, designation, kind, num, position, sexagesimal
from wiki2yaml import LINK, REF

COUNT = 313
# Compendium rows past the tolerance whose position SIMBAD confirms (modern
# position within 5'), where Sharpless's own is the one that is off.
TRUSTED = {4, 20}  # Sharpless 16' and 28' off


def sharpless(path):
    """Sh2 number -> (RA deg, Dec deg, diameter arcmin) from the VizieR TSV."""
    out, cols = {}, None
    for line in open(path, encoding="utf-8"):
        f = [c.strip() for c in line.rstrip("\n").split("\t")]
        if line.startswith("#") or len(f) < 2:
            continue
        if cols is None:
            cols = {c: i for i, c in enumerate(f)}
        elif f[cols["Sh2"]].isdigit():
            n = int(f[cols["Sh2"]])
            out[n] = (float(f[cols["_RAJ2000"]]), float(f[cols["_DEJ2000"]]), float(f[cols["Diam"]]))
    if sorted(out) != list(range(1, COUNT + 1)):
        sys.exit(f"error: want Sh2 1-{COUNT} once each, got {len(out)} rows")
    return out


def common_names(path):
    """Sh2 number -> common name from the Wikipedia table (notable objects only)."""
    out = {}
    for chunk in open(path, encoding="utf-8").read().split("\n|-"):
        line = chunk.strip().splitlines()[0] if chunk.strip() else ""
        cells = [" ".join(LINK.sub(r"\1", REF.sub(" ", c)).split()) for c in line.lstrip("| ").split("||")]
        m = re.fullmatch(r"Sh 2-(\d+)", cells[0])
        if m and len(cells) > 1 and cells[1] and not re.fullmatch(r"(Sh ?2|Sharpless) ?-?\d+", cells[1]):
            out[int(m.group(1))] = cells[1]
    return out


def sep(ra1, dec1, ra2, dec2):
    """Separation in arcminutes; flat-sky is fine for the tens-of-arcminutes tolerance."""
    dra = (ra1 - ra2 + 180) % 360 - 180
    return math.hypot(dra * math.cos(math.radians(dec2)), dec1 - dec2) * 60


def match(n, ra, dec, diam, index):
    """The Compendium row for Sh2-N and whether it is the Sharpless object
    itself (named Sh2-N, or carrying it as an alternative ID), or None."""
    own = index.get(f"Sh2-{n}", [])
    for rows, itself in ((own, True), ([r for r in index.get(f"Sh 2-{n}", []) if r not in own], False)):
        # The exact name first (V0628 Cas also lists Sh2-157), then the nearest.
        for r in sorted(rows, key=lambda r: (designation(r["A"]) != f"Sh2-{n}", sep(*position(r), ra, dec))):
            d = sep(*position(r), ra, dec)
            if d <= max(20, diam / 2) or n in TRUSTED:
                return r, itself
            print(f"warning: Sh2-{n}: Compendium {r['A'].strip()} is {d:.0f}' away, ignored", file=sys.stderr)
    return None, False


def main():
    cat, common, index = sharpless(sys.argv[1]), common_names(sys.argv[2]), aliases(sys.argv[3])
    q = lambda s: json.dumps(s, ensure_ascii=False)  # JSON strings are valid YAML
    print("# Generated by scripts/sharpless2yaml.py: the Sharpless (1959) catalogue (CDS VII/20),")
    print("# cross-identified with Gary Imm's Deep Sky Compendium (2026) - data (c) Gary Imm.")
    out = []
    for n, (ra, dec, diam) in sorted(cat.items()):
        r, itself = match(n, ra, dec, diam, index)
        typ, mag, surfbr, size, desc = "Emission Nebula", None, None, diam, []
        if r:
            ra, dec = position(r)
            typ, mag, surfbr = kind(r), num(r.get("T")), num(r.get("U"))
            if itself and num(r.get("G")):
                size = num(r["G"])
            # "Butterfly Nebula (3 of 3)": the Compendium's own split of a nebula.
            nick = re.sub(r"\s*\(\d+ ?of ?\d+\)", "", " ".join((r.get("Q") or "").split()))
            desc = [designation(r["A"])] + re.split(r"\s*,\s*", nick)
        out.append((n, ra, dec, size, typ, mag, surfbr, [d for d in dict.fromkeys(desc) if d and d != f"Sh2-{n}"]))
    # Wikipedia's name only where the Compendium gives it to no object
    # (it calls Sh2-113 the Flying Dragon, the Compendium Sh2-114).
    named = {d.lower() for o in out for d in o[-1]}
    for n, ra, dec, size, typ, mag, surfbr, desc in out:
        if n in common and common[n].lower() not in named:
            desc.append(common[n])
        print('- constellation: ""')  # the loader computes it from RA/Dec
        print(f"  dec: {q(sexagesimal(dec))}")
        print(f"  description: {q(', '.join(desc))}")
        print(f"  mag: {mag if mag is not None else -9999}")
        print(f"  name: {q(f'Sh2-{n}')}")
        print(f"  ra: {q(sexagesimal(ra, hours=True))}")
        print(f"  size: {size}")
        if surfbr is not None:
            print(f"  surfbr: {round(surfbr, 2)}")
        print(f"  type: {q(typ)}")


if __name__ == "__main__":
    main()
